name: PRs to master
on:
  pull_request:
    branches: [master]
    types: [closed]
jobs:
  merge-master-back-to-dev:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Git config
        run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Merge master back to dev
        run: |
          git fetch --unshallow
          git checkout dev
          git pull
          git merge --no-ff master -m "Auto-merge master back to dev"
          git push
